### ISSUE TITLE
Support alternate msqc for queue manager instance

### ISSUE THREAD

**Issue by timroster** [cloud-native-toolkit/terraform-gitops-cp-queue-manager#17]
We have an Integration Accelerator workshop that would be good to support with automation from the queue-manager module. However, the workshop opinions mean that a specific mqsc (vs. the default) needs to be set in the queue-manager configmap

ex:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: qmtrader-mqsc
  namespace: cp4i-mq
data:
  config.mqsc: |-
   DEFINE QLOCAL(STUDENT001.QUEUE) REPLACE
   DEFINE CHANNEL(TRADER.TO.MQ) CHLTYPE(SVRCONN) TRPTYPE(TCP)
   ALTER QMGR CHLAUTH (DISABLED)
   ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) CHCKCLNT(NONE)
   REFRESH SECURITY TYPE(CONNAUTH)
```

Although the `config_map` name is a variable, this map appears to be propagated with static file content from the chart.
